cache:
  directories:
  - $HOME/.m2
language: java
jdk:
- oraclejdk8
script: ./build.sh
after_success:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc -out $GPG_DIR/pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc -out $GPG_DIR/secring.gpg -d
- $GPG_DIR/publish.sh
env:
  global:
  - GPG_DIR="`pwd`/deploy"
  - secure: rAOkBDXPV64tAWeRAVl/lBRy3nt+aV5BmHYkWdIkZy/u3sMNcdT9yFCW7OHA6hACaGckYi0rHQHUGB5hLneoLd0ga76MTkSFYtIfGKumqRGAVFVUIuCYeTjfkVWykh6Yiej8warRVtPyOuD3Bol+mSzHJs4lSTRZBuBXNowF5aHr9z77uZIPOlhqukBWOZmfmx7rXVNIuxdVpJvrDvvhd/WLUlrLk4heXqpgTw1y5uJAkI2JN54i6hCLEpyO2c4R6EVfNqljjxigXoa/lYNB9dFnMpcfuFnM3quXBqratSWsjJUtYVS7bn0qR1bVnXpC1J1eKKhTGvVJ6Fpucts8BvS308VwkxQmKt8Vt0A4baGSplzKhhPt4K0JiXXqmWZJNR7+TWP4kxc0HY83hgaGvRBFXoigROtJac3G5a0X6IqqPwmoC8YYaN8/4vIfRjXQOlO9qnjorwtR81XNDrt3K/ycR2PHV1pHof60PdNI5/OegDvaxOVdIj5ygdZ9tmJEZepzro4ZGtxOMUgIwMPMa/SBPE9V3MJjMjTsGPSKk3k0q7QEtfQydJmHZ9v8VVqoqA+b9IkQdWfh3FTSVKgoL0EoLiz/x43N/r3BxyfdQo5U+qIlnhKmrF2UbTFaDRNtN2gNEMb+sul7wrMHg8DV2yHuCxghvb2261xApU6ZRV8=
